apiVersion: v1
kind: Service
metadata:
  name: episode4-backend-service
  labels:
    app: episode4-backend
spec:
  selector:
    app: episode4-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort