apiVersion: v1
kind: Service
metadata:
  name: episode3-backend-service
  labels:
    app: episode3-backend
spec:
  selector:
    app: episode3-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort