apiVersion: v1
kind: Service
metadata:
  name: episode5-frontend-service
  labels:
    app: episode5-frontend
spec:
  selector:
    app: episode5-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort