apiVersion: v1
kind: Service
metadata:
  name: episode2-backend-service
  labels:
    app: episode2-backend
spec:
  selector:
    app: episode2-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort