apiVersion: apps/v1
kind: Deployment
metadata:
  name: episode2-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: episode2-frontend
  template:
    metadata:
      labels:
        app: episode2-frontend
    spec:
      containers:
        - name: episode2-frontend
          image: episode2_frontend
          ports:
            - containerPort: 81
