apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-volume-episode-02
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/db/data-episode-02"
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-claim-episode-02
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi