apiVersion: apps/v1
kind: Deployment
metadata:
  name: episode1-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: episode1-backend
  template:
    metadata:
      labels:
        app: episode1-backend
    spec:
      containers:
        - name: episode1-backend
          image: fatimaqurban95/episode1_backend
          ports:
            - containerPort: 3000
           env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_URI
          volumeMounts:
            - name: db-volume-episode-01
              mountPath: /data/db
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: db-claim-episode-01
